In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('C:\\Workspace\\machine learning\\linear regression multi\\excercise\\hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
df.experience=df.experience.replace({
    0:'zero'
})
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [25]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [20]:
from word2number import w2n

In [27]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [29]:

median_experience=df.experience.median()
median_experience

4.0

In [30]:
df.experience=df.experience.replace({
    0:median_experience
})
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         4.0                    8.0                           9      50000
1         4.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [34]:
median_testscore=df['test_score(out of 10)'].median()
median_testscore

8.0

In [36]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(median_testscore)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         4.0                    8.0                           9      50000
1         4.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    8.0                           7      72000
7        11.0                    7.0                           8      80000

In [38]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df[['salary($)']])

LinearRegression()

In [39]:
reg.predict([[6.0,9.0,8]])

array([[66274.68839885]])

In [40]:
reg.coef_


array([[3390.87422644, 1803.45158198, 3184.69450013]])

In [41]:
reg.intercept_


array([4220.82280136])