In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df=pd.read_csv('C:\\Workspace\\machine learning\\linear regression\\homeprices.csv')
df


area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [22]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']],df[['price']])

LinearRegression()

In [23]:
reg.coef_

array([[135.78767123]])

In [24]:
reg.intercept_


array([180616.43835616])

In [25]:
y=reg.predict([[3300]])
print(y)

[[628715.75342466]]


In [26]:
d=pd.read_csv('C:\\Workspace\\machine learning\\linear regression\\areas.csv')
d

area
0   1000
1   1500
2   2300
3   3540
4   4120
5   4560
6   5490
7   3460
8   4750
9   2300
10  9000
11  8600
12  7100

In [29]:
p=reg.predict(d)
p

array([[ 316404.10958904],
       [ 384297.94520548],
       [ 492928.08219178],
       [ 661304.79452055],
       [ 740061.64383562],
       [ 799808.21917808],
       [ 926090.75342466],
       [ 650441.78082192],
       [ 825607.87671233],
       [ 492928.08219178],
       [1402705.47945205],
       [1348390.4109589 ],
       [1144708.90410959]])

In [30]:
d['prices']=p

In [33]:
d.to_csv('predictions.csv')